/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-12-13")
public class Data implements org.apache.thrift.TBase<Data, Data._Fields>, java.io.Serializable, Cloneable, Comparable<Data> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Data");

  private static final org.apache.thrift.protocol.TField MAT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("matCode", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PROJECT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("projectCode", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DataTupleSchemeFactory());
  }

  public String matCode; // required
  public String projectCode; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MAT_CODE((short)1, "matCode"),
    PROJECT_CODE((short)2, "projectCode");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MAT_CODE
          return MAT_CODE;
        case 2: // PROJECT_CODE
          return PROJECT_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MAT_CODE, new org.apache.thrift.meta_data.FieldMetaData("matCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROJECT_CODE, new org.apache.thrift.meta_data.FieldMetaData("projectCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Data.class, metaDataMap);
  }

  public Data() {
  }

  public Data(
    String matCode,
    String projectCode)
  {
    this();
    this.matCode = matCode;
    this.projectCode = projectCode;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Data(Data other) {
    if (other.isSetMatCode()) {
      this.matCode = other.matCode;
    }
    if (other.isSetProjectCode()) {
      this.projectCode = other.projectCode;
    }
  }

  public Data deepCopy() {
    return new Data(this);
  }

  @Override
  public void clear() {
    this.matCode = null;
    this.projectCode = null;
  }

  public String getMatCode() {
    return this.matCode;
  }

  public Data setMatCode(String matCode) {
    this.matCode = matCode;
    return this;
  }

  public void unsetMatCode() {
    this.matCode = null;
  }

  /** Returns true if field matCode is set (has been assigned a value) and false otherwise */
  public boolean isSetMatCode() {
    return this.matCode != null;
  }

  public void setMatCodeIsSet(boolean value) {
    if (!value) {
      this.matCode = null;
    }
  }

  public String getProjectCode() {
    return this.projectCode;
  }

  public Data setProjectCode(String projectCode) {
    this.projectCode = projectCode;
    return this;
  }

  public void unsetProjectCode() {
    this.projectCode = null;
  }

  /** Returns true if field projectCode is set (has been assigned a value) and false otherwise */
  public boolean isSetProjectCode() {
    return this.projectCode != null;
  }

  public void setProjectCodeIsSet(boolean value) {
    if (!value) {
      this.projectCode = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MAT_CODE:
      if (value == null) {
        unsetMatCode();
      } else {
        setMatCode((String)value);
      }
      break;

    case PROJECT_CODE:
      if (value == null) {
        unsetProjectCode();
      } else {
        setProjectCode((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MAT_CODE:
      return getMatCode();

    case PROJECT_CODE:
      return getProjectCode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MAT_CODE:
      return isSetMatCode();
    case PROJECT_CODE:
      return isSetProjectCode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Data)
      return this.equals((Data)that);
    return false;
  }

  public boolean equals(Data that) {
    if (that == null)
      return false;

    boolean this_present_matCode = true && this.isSetMatCode();
    boolean that_present_matCode = true && that.isSetMatCode();
    if (this_present_matCode || that_present_matCode) {
      if (!(this_present_matCode && that_present_matCode))
        return false;
      if (!this.matCode.equals(that.matCode))
        return false;
    }

    boolean this_present_projectCode = true && this.isSetProjectCode();
    boolean that_present_projectCode = true && that.isSetProjectCode();
    if (this_present_projectCode || that_present_projectCode) {
      if (!(this_present_projectCode && that_present_projectCode))
        return false;
      if (!this.projectCode.equals(that.projectCode))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_matCode = true && (isSetMatCode());
    list.add(present_matCode);
    if (present_matCode)
      list.add(matCode);

    boolean present_projectCode = true && (isSetProjectCode());
    list.add(present_projectCode);
    if (present_projectCode)
      list.add(projectCode);

    return list.hashCode();
  }

  @Override
  public int compareTo(Data other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMatCode()).compareTo(other.isSetMatCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMatCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.matCode, other.matCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProjectCode()).compareTo(other.isSetProjectCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProjectCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.projectCode, other.projectCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Data(");
    boolean first = true;

    sb.append("matCode:");
    if (this.matCode == null) {
      sb.append("null");
    } else {
      sb.append(this.matCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("projectCode:");
    if (this.projectCode == null) {
      sb.append("null");
    } else {
      sb.append(this.projectCode);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DataStandardSchemeFactory implements SchemeFactory {
    public DataStandardScheme getScheme() {
      return new DataStandardScheme();
    }
  }

  private static class DataStandardScheme extends StandardScheme<Data> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Data struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MAT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.matCode = iprot.readString();
              struct.setMatCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROJECT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.projectCode = iprot.readString();
              struct.setProjectCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Data struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.matCode != null) {
        oprot.writeFieldBegin(MAT_CODE_FIELD_DESC);
        oprot.writeString(struct.matCode);
        oprot.writeFieldEnd();
      }
      if (struct.projectCode != null) {
        oprot.writeFieldBegin(PROJECT_CODE_FIELD_DESC);
        oprot.writeString(struct.projectCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DataTupleSchemeFactory implements SchemeFactory {
    public DataTupleScheme getScheme() {
      return new DataTupleScheme();
    }
  }

  private static class DataTupleScheme extends TupleScheme<Data> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Data struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMatCode()) {
        optionals.set(0);
      }
      if (struct.isSetProjectCode()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMatCode()) {
        oprot.writeString(struct.matCode);
      }
      if (struct.isSetProjectCode()) {
        oprot.writeString(struct.projectCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Data struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.matCode = iprot.readString();
        struct.setMatCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.projectCode = iprot.readString();
        struct.setProjectCodeIsSet(true);
      }
    }
  }

}

