/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ASN : TBase
{

  public string Code { get; set; }

  public string Project_Code { get; set; }

  public string Order_Date { get; set; }

  public string Vendor_Name { get; set; }

  public string Apply_Person { get; set; }

  public string Releated_Bill1 { get; set; }

  public ASN() {
  }

  public ASN(string Code, string Project_Code, string Order_Date, string Vendor_Name, string Apply_Person, string Releated_Bill1) : this() {
    this.Code = Code;
    this.Project_Code = Project_Code;
    this.Order_Date = Order_Date;
    this.Vendor_Name = Vendor_Name;
    this.Apply_Person = Apply_Person;
    this.Releated_Bill1 = Releated_Bill1;
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      bool isset_Code = false;
      bool isset_Project_Code = false;
      bool isset_Order_Date = false;
      bool isset_Vendor_Name = false;
      bool isset_Apply_Person = false;
      bool isset_Releated_Bill1 = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Code = iprot.ReadString();
              isset_Code = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Project_Code = iprot.ReadString();
              isset_Project_Code = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Order_Date = iprot.ReadString();
              isset_Order_Date = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Vendor_Name = iprot.ReadString();
              isset_Vendor_Name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Apply_Person = iprot.ReadString();
              isset_Apply_Person = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Releated_Bill1 = iprot.ReadString();
              isset_Releated_Bill1 = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_Code)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Project_Code)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Order_Date)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Vendor_Name)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Apply_Person)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_Releated_Bill1)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ASN");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "Code";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Code);
      oprot.WriteFieldEnd();
      field.Name = "Project_Code";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Project_Code);
      oprot.WriteFieldEnd();
      field.Name = "Order_Date";
      field.Type = TType.String;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Order_Date);
      oprot.WriteFieldEnd();
      field.Name = "Vendor_Name";
      field.Type = TType.String;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Vendor_Name);
      oprot.WriteFieldEnd();
      field.Name = "Apply_Person";
      field.Type = TType.String;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Apply_Person);
      oprot.WriteFieldEnd();
      field.Name = "Releated_Bill1";
      field.Type = TType.String;
      field.ID = 6;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Releated_Bill1);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ASN(");
    __sb.Append(", Code: ");
    __sb.Append(Code);
    __sb.Append(", Project_Code: ");
    __sb.Append(Project_Code);
    __sb.Append(", Order_Date: ");
    __sb.Append(Order_Date);
    __sb.Append(", Vendor_Name: ");
    __sb.Append(Vendor_Name);
    __sb.Append(", Apply_Person: ");
    __sb.Append(Apply_Person);
    __sb.Append(", Releated_Bill1: ");
    __sb.Append(Releated_Bill1);
    __sb.Append(")");
    return __sb.ToString();
  }

}

